//@version=5
strategy("EMA Crossover Strategy", overlay=true)

// indicators
emaFast = ta.ema(close, 50)
emaSlow = ta.ema(close, 200)

// conditions
buySignal  = ta.crossover(emaFast, emaSlow)
sellSignal = ta.crossunder(emaFast, emaSlow)

// execute trades
if buySignal
    strategy.entry("BUY", strategy.long)

if sellSignal
    strategy.close("BUY")

// plots
plot(emaFast, color=color.orange)
plot(emaSlow, color=color.blue)
